name: Contract Deployment template

on:
  workflow_call:
    inputs:
      NETWORK:
        required: true
        type: string
        description: "Network"
      MUMBAI_PROVIDER_URL:
        required: true
        type: string
        description: "Polygon Mumbai provider URL"
      POLYGON_MAINNET_PROVIDER_URL:
        required: true
        type: string
        description: "Polygon Mainnet provider URL"
      DEPLOYMENT_MNEMONIC:
        required: true
        type: string
        description: "Deployment Mnemonic"
      SALT:
        required: true
        type: string
        description: "Salt for deterministic deployments"

env:
  MUMBAI_PROVIDER_URL: ${{ inputs.MUMBAI_PROVIDER_URL }}
  POLYGON_MAINNET_PROVIDER_URL: ${{ inputs.POLYGON_MAINNET_PROVIDER_URL }}
  DEPLOYMENT_MNEMONIC: ${{ inputs.DEPLOYMENT_MNEMONIC }}
  SALT: ${{ inputs.SALT }}
  PNPM_VERSION: 8.15.2
  NODE_VERSION: 20.11.0

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.NPM_TOKEN }}
          ref: main

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Build
        run: |
          pnpm run build:contracts
          pnpm --filter @nexeraprotocol/nexera-id-sig-gating-contracts-sdk build

      # Commented for now because we prefer to bump it manually
      #   - name: Update Signer Manager version
      #     run: |
      #       pnpm run version:patch

      - name: Deploy contracts
        run: pnpm deploy-${{ inputs.NETWORK }}

      - name: Update deployed addresses in sdk
        run: |
          pnpm copy-info-to-sdk
          pnpm lint

      - name: Create branch
        run: git checkout -b contracts/${{ inputs.NETWORK }}-deployment-${{ github.run_number }}

      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com

      - name: Prepare commit
        run: |
          git add .
          git commit -m "Update ${{ inputs.NETWORK }} deployment"

      - name: Push new branch
        run: git push origin contracts/${{ inputs.NETWORK }}-deployment-${{ github.run_number }}

      - name: Create pull request into main branch
        uses: thomaseizinger/create-pull-request@1.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          head: contracts/${{ inputs.NETWORK }}-deployment-${{ github.run_number }}
          base: main
          title: contracts/${{ inputs.NETWORK }}-deployment-${{ github.run_number }} into main
          body: |
            Automated pull request: This PR was created in response workflow running.
