name: Deploy testnet contracts

on:
  workflow_dispatch:

jobs:
  deploy:
    strategy:
      #      max-parallel: 1 # Avoid weird issues with git when some run pushes in the meantime the other is running.
      matrix:
        network:
          - sepolia
          - polygonAmoy
          - baseSepolia
          - optimisticSepolia
          - avalancheFujiTestnet
          - bscTestnet
          - arbitrumSepolia
    uses: ./.github/workflows/deploy-template.yml
    with:
      NETWORK: ${{ matrix.network }}
    secrets: inherit
