name: SDK Release

on:
  push:
    branches:
      - development

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.9.0]
        pnpm-version: [8.10.2]
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.MERGE_BOT_APP_ID }}
          private_key: ${{ secrets.MERGE_BOT_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.generate_token.outputs.token }}
          fetch-depth: 0

      - uses: pnpm/action-setup@v2.4.0
        name: Install pnpm
        id: pnpm-install
        with:
          version: ${{ matrix.pnpm-version }}
          run_install: false

      - uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: |
          pnpm install

      - name: Config github actions user
        run: |
          git config --global user.name "nexera-release[bot]"
          git config --global user.email "137495321+nexera-release[bot]@users.noreply.github.com"

      - name: Update branch protection for Lerna
        shell: bash
        run: |
          curl -s -L -o /dev/null \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.MERGE_BOT_ACCESS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -d '{
            "required_status_checks":{
            "strict":true,
            "contexts":[
            "Generate API client",
            "Generate CMS client",
            "Docker build - API",
            "Docker build - CMS",
            "Docker build - Data Analytics",
            "Docker build - UI tests",
            "Docker build - ZK Verifier",
            "Lint",
            "Unit tests",
            "Frontend tests",
            "Vercel – landing-b2b",
            "Vercel – nexera-id-docs",
            "Vercel – nexera-id-dashboard",
            "Vercel – nexera-id-example-dapp",
            "Vercel – nexera-id-identity-app",
            "Vercel Preview Comments"
            ]
            },
            "enforce_admins":false,
            "required_pull_request_reviews":{
            "dismissal_restrictions":{},
            "dismiss_stale_reviews":false,
            "require_code_owner_reviews":true,
            "required_approving_review_count":1,
            "require_last_push_approval":false,
            "bypass_pull_request_allowances":{"apps":["nexera-release"],"teams":[],"users":[]}},
            "restrictions":null,
            "required_linear_history":false,
            "allow_force_pushes":false,
            "allow_deletions":false,
            "block_creations":false,
            "required_conversation_resolution":false,
            "lock_branch":false,
            "allow_fork_syncing":true
            }' \
            https://api.github.com/repos/NexeraProtocol/NexeraID/branches/development/protection

      - name: Bump versions and update changelog
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          lerna version --yes --changelog-preset=angular

      - name: Update branch protection
        shell: bash
        run: |
          curl -s -L -o /dev/null \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.MERGE_BOT_ACCESS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -d '{
            "required_status_checks":{
            "strict":true,
            "contexts":[
            "Generate API client",
            "Generate CMS client",
            "Docker build - API",
            "Docker build - CMS",
            "Docker build - Data Analytics",
            "Docker build - UI tests",
            "Docker build - ZK Verifier",
            "Lint",
            "Unit tests",
            "Frontend tests",
            "Vercel – landing-b2b",
            "Vercel – nexera-id-docs",
            "Vercel – nexera-id-dashboard",
            "Vercel – nexera-id-example-dapp",
            "Vercel – nexera-id-identity-app",
            "Vercel Preview Comments"
            ]
            },
            "enforce_admins":true,
            "required_pull_request_reviews":{
            "dismissal_restrictions":{},
            "dismiss_stale_reviews":false,
            "require_code_owner_reviews":true,
            "required_approving_review_count":1,
            "require_last_push_approval":false,
            "bypass_pull_request_allowances":{"apps":["nexera-release"],"teams":[],"users":[]}},
            "restrictions":null,
            "required_linear_history":false,
            "allow_force_pushes":false,
            "allow_deletions":false,
            "block_creations":false,
            "required_conversation_resolution":false,
            "lock_branch":false,
            "allow_fork_syncing":true
            }' \
            https://api.github.com/repos/NexeraProtocol/NexeraID/branches/development/protection

      - name: Build
        run: |
          pnpm run build:cms-client
          pnpm run build:api-client
          pnpm run build:did-vc-holder
          pnpm run build:did-vc-issuer
          pnpm run build:did-vc-verifier
          pnpm run build:identity-sdk
          pnpm run build:notifications
          pnpm run build:schemas
          pnpm run build:vault
      - name: Publish to npm
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pnpm --filter "@nexeraprotocol/api-client" publish --no-git-checks --registry https://npm.pkg.github.com/
          pnpm --filter "@nexeraprotocol/cms-client" publish --no-git-checks --registry https://npm.pkg.github.com/
          pnpm --filter "@nexeraprotocol/did-vc-holder" publish --no-git-checks --registry https://npm.pkg.github.com/
          pnpm --filter "@nexeraprotocol/did-vc-issuer" publish --no-git-checks --registry https://npm.pkg.github.com/
          pnpm --filter "@nexeraprotocol/nexera-id-notifications" publish --no-git-checks --registry https://npm.pkg.github.com/
          pnpm --filter "@nexeraprotocol/nexera-id-schemas" publish --no-git-checks --registry https://npm.pkg.github.com/
          pnpm --filter "@nexeraprotocol/nexera-id-vault" publish --no-git-checks --registry https://npm.pkg.github.com/

      - name: Publish to public npm
        env:
          NPMJS_COM_TOKEN: ${{secrets.NPMJS_COM_TOKEN}}
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPMJS_COM_TOKEN" > .npmrc
          pnpm --filter "@nexeraid/identity-sdk" prepare:release
          pnpm --filter "@nexeraid/identity-sdk" publish --access=public --no-git-checks --registry https://registry.npmjs.org/

          pnpm --filter "@nexeraprotocol/nexera-id-schemas" prepare:release
          pnpm --filter "@nexeraprotocol/nexera-id-schemas" publish --access=public --no-git-checks --registry https://registry.npmjs.org/
