name: SDK Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.9.0]
        pnpm-version: [8.10.2]
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.MERGE_BOT_APP_ID }}
          private_key: ${{ secrets.MERGE_BOT_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.generate_token.outputs.token }}
          fetch-depth: 0

      - uses: pnpm/action-setup@v2.4.0
        name: Install pnpm
        id: pnpm-install
        with:
          version: ${{ matrix.pnpm-version }}
          run_install: false

      - uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: |
          pnpm install

      - name: Config github actions user
        run: |
          git config --global user.name "nexera-release[bot]"
          git config --global user.email "137495321+nexera-release[bot]@users.noreply.github.com"

      - name: Bump versions and update changelog
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          lerna version --yes --changelog-preset=angular

      - name: Build
        env:
          MUMBAI_PROVIDER_URL: ${{ secrets.MUMBAI_PROVIDER_URL }}
          MUMBAI_PRIVATE_KEY: ${{ secrets.MUMBAI_PRIVATE_KEY }}
          MUMBAI_PRIVATE_KEY2: ${{ secrets.MUMBAI_PRIVATE_KEY2 }}
        run: |
          pnpm run build:hardhat

      - name: Publish to npm
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pnpm --filter "@nexeraid/contracts" publish --no-git-checks --registry https://npm.pkg.github.com/
