name: Build

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

env:
  MUMBAI_PROVIDER_URL: ${{ secrets.MUMBAI_PROVIDER_URL }}
  TEST_MNEMONIC: ${{ secrets.TEST_MNEMONIC }}
  POLYGON_MAINNET_PROVIDER_URL: ${{ secrets.POLYGON_MAINNET_PROVIDER_URL }}
  DEPLOYMENT_MNEMONIC: ${{ secrets.DEPLOYMENT_MNEMONIC }}
  PNPM_VERSION: 8.14.0
  NODE_VERSION: 20.9.0

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-test-build
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ env.NPM_TOKEN }}

      - uses: pnpm/action-setup@v2.4.0
        name: Install pnpm
        id: pnpm-install
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies
        run: |
          pnpm install

      - name: Build contracts
        env:
          MUMBAI_PROVIDER_URL: ${{ secrets.MUMBAI_PROVIDER_URL }}
          TEST_MNEMONIC: ${{ secrets.TEST_MNEMONIC }}
          POLYGON_MAINNET_PROVIDER_URL: ${{ secrets.POLYGON_MAINNET_PROVIDER_URL }}
          DEPLOYMENT_MNEMONIC: ${{ secrets.DEPLOYMENT_MNEMONIC }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pnpm run build:hardhat

      - name: Build contracts SDK
        env:
          MUMBAI_PROVIDER_URL: ${{ secrets.MUMBAI_PROVIDER_URL }}
          TEST_MNEMONIC: ${{ secrets.TEST_MNEMONIC }}
          POLYGON_MAINNET_PROVIDER_URL: ${{ secrets.POLYGON_MAINNET_PROVIDER_URL }}
          DEPLOYMENT_MNEMONIC: ${{ secrets.DEPLOYMENT_MNEMONIC }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pnpm --filter @nexeraprotocol/nexera-id-contracts-sdk build
