name: 🖥️🧪 Unit test

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

env:
  AMOY_PROVIDER_URL: ${{ secrets.AMOY_PROVIDER_URL }}
  TEST_MNEMONIC: ${{ secrets.TEST_MNEMONIC }}
  POLYGON_MAINNET_PROVIDER_URL: ${{ secrets.POLYGON_MAINNET_PROVIDER_URL }}
  MAINNET_SIG_DEPLOYMENT_MNEMONIC: ${{ secrets.MAINNET_SIG_DEPLOYMENT_MNEMONIC }}
  SALT: ${{ secrets.SALT }}
  PNPM_VERSION: 9.1.4
  NODE_VERSION: 20.14

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    name: Unit tests
    environment:
      name: vc-dev
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - uses: pnpm/action-setup@v3.0.0
        name: Install pnpm
        id: pnpm-install
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: 🖥️🧪 Run unit test
        continue-on-error: false
        run: |
          pnpm run test:unit

      - uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          node-version: 18.12

      - name: Start a sandbox for Tezos (on local network)
        continue-on-error: false
        run: |
          cd tezos-sig-gating-contracts
          make sandbox-start

      - name: 🖥️🧪 Run integration test for Tezos (on local network)
        continue-on-error: false
        run: |
          pnpm run test:tezos-contracts-sdk

      - name: 🖥️🧪 Stop the sandbox for Tezos (on local network)
        if: always()
        continue-on-error: false
        run: |
          cd tezos-sig-gating-contracts
          make sandbox-stop
